# Generated by Django 2.2.28 on 2025-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
