# Generated by Django 2.2.28 on 2025-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0002_artist_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
