# Generated by Django 2.2.28 on 2025-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0003_artist_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
