# Generated by Django 2.2.28 on 2025-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0004_auto_20250318_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_preview_url',
            new_name='preview_url',
        ),
    ]
