# Generated by Django 2.2.28 on 2025-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0005_auto_20250319_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
