# Generated by Django 2.2.28 on 2025-03-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0006_auto_20250319_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='preview_url',
        ),
    ]
