# Generated by Django 2.2.28 on 2025-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0007_remove_song_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
