# Generated by Django 2.2.28 on 2025-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0008_song_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
