# Generated by Django 2.2.28 on 2025-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0009_song_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
