# Generated by Django 2.2.28 on 2025-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0010_review_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='view_count',
            new_name='play_count',
        ),
    ]
