# Generated by Django 2.2.28 on 2025-03-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0011_auto_20250321_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='play_count',
            new_name='view_count',
        ),
    ]
