# Generated by Django 2.2.28 on 2025-03-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0013_song_song_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_preview_url',
        ),
    ]
