# Generated by Django 2.2.28 on 2025-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0015_auto_20250326_1611'),
        ('drop_the_beat', '0014_remove_song_song_preview_url'),
    ]

    operations = [
    ]
