# Generated by Django 2.2.28 on 2025-03-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0016_merge_20250326_1642'),
        ('drop_the_beat', '0016_merge_20250326_1636'),
    ]

    operations = [
    ]
