# Generated by Django 2.2.28 on 2025-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0020_auto_20250326_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
