# Generated by Django 2.2.28 on 2025-03-27 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drop_the_beat', '0021_auto_20250326_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs_uploaded', to='drop_the_beat.UserProfile'),
        ),
    ]
